# -*- coding: utf-8 -*-
"""Islanding_Detection_Pipeline_MLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F7jaZjYsYNQ4519ThJuCIE4yqbPXb5D9

# 🔌 Islanding Detection Pipeline
**Goal:** Detect islanding vs grid-connected events using DWT + MLP

- Dataset: 5 islanding zone files (1,785 recordings)
- Sampling rate: 3840 Hz
- Window size: 64 samples (1 cycle at 60Hz)
- Wavelet: Sym4, Level 3
- Split: 60% train / 20% validation / 20% test


#**Sections:**
# PHASE 0 — Imports and Configuration
- PHASE A — Data Preparation
- PHASE B — Cycle-by-Cycle Windowing
- PHASE C — DWT Feature Extraction
- PHASE D — Classifier Training
- PHASE E — Evaluation
"""

from google.colab import drive
drive.mount('/content/drive')

# ═══════════════════════════════════════════════════════
#  IMPORTS
# ═══════════════════════════════════════════════════════
import numpy as np
import scipy.io
import pywt
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE
from scipy.stats import spearmanr
import os
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, sigmoid, relu



DATA_PATH    = '/content/drive/MyDrive/Final Year Project/Islanding_project/Dataset/Islanding-Detection-in-Colab/Dataset/Voltage/'
FIGURES_PATH = '/content/drive/MyDrive/Final Year Project/Islanding_project/Dataset/Islanding-Detection-in-Colab/Outputs/Figures/'
MODELS_PATH  = '/content/drive/MyDrive/Final Year Project/Islanding_project/Dataset/Islanding-Detection-in-Colab/Outputs/models/'

print("✓ Imports loaded")
print(f"  Data path    : {DATA_PATH}")
print(f"  Figures path : {FIGURES_PATH}")
print(f"  Models path  : {MODELS_PATH}")

print("Checking data files...")
print("=" * 50)

islanding_files = [
    'V_zone1_numeric.mat',
    'V_zone2_numeric.mat',
    'V_zone3_numeric.mat',
    'V_zone4_numeric.mat',
    'V_zone12_numeric.mat',
    'Vb1LG_numeric.mat',
    'Vb1LLG_numeric.mat',
    'Vb1LLLG_numeric.mat',
    'Vb1nicw_numeric.mat',
    'Vb1nilsw_numeric.mat',
    'Vb2LG_numeric.mat',
    'Vb2LLG_numeric.mat',
    'Vb2LLLG_numeric.mat',
    'Vb2nicw_numeric.mat',
    'Vb3nicw_numeric.mat',
    'Vb3nilsw_numeric.mat',
    'Vb4nicw_numeric.mat',
    'Vb4nilsw_numeric.mat',
    'Vb6nicw_numeric.mat',
]

all_found = True
for f in islanding_files:
    full_path = DATA_PATH + f
    exists    = os.path.exists(full_path)
    status    = "✓ found" if exists else "✗ NOT FOUND"
    print(f"  {f:<30} {status}")
    if not exists:
        all_found = False

print("=" * 50)
if all_found:
    print("✓ All files found — ready to proceed")
else:
    print("✗ Some files missing — check your data folder path")

import numpy as np

# Load one of your raw .mat files and check the voltage magnitude
import scipy.io as sio

# Replace with the path to any one of your 19 .mat files
mat = sio.loadmat('/content/drive/MyDrive/Final Year Project/Islanding_project/Dataset/Islanding-Detection-in-Colab/Dataset/Voltage/V_zone1_numeric.mat')
cell_out = mat['cell_out']

print(f"Type:  {type(cell_out)}")
print(f"Shape: {cell_out.shape}")
print(f"Dtype: {cell_out.dtype}")

# Peek inside — cell arrays in scipy come as object arrays
print(f"\nFirst element type:  {type(cell_out.flat[0])}")
print(f"First element shape: {cell_out.flat[0].shape}")
print(f"First element:\n{cell_out.flat[0]}")

data = cell_out.flat[0]

time = data[:, 0]
Va   = data[:, 1]
Vb   = data[:, 2]
Vc   = data[:, 3]

# RMS per phase
Va_rms = np.sqrt(np.mean(Va**2))
Vb_rms = np.sqrt(np.mean(Vb**2))
Vc_rms = np.sqrt(np.mean(Vc**2))

# Peak per phase
Va_peak = np.max(np.abs(Va))
Vb_peak = np.max(np.abs(Vb))
Vc_peak = np.max(np.abs(Vc))

print(f"{'='*45}")
print(f"  Voltage Analysis — Recording 1")
print(f"{'='*45}")
print(f"  {'Phase':<10} {'RMS (V)':>12} {'Peak (V)':>12}")
print(f"  {'-'*36}")
print(f"  {'Va':<10} {Va_rms:>12.4f} {Va_peak:>12.4f}")
print(f"  {'Vb':<10} {Vb_rms:>12.4f} {Vb_peak:>12.4f}")
print(f"  {'Vc':<10} {Vc_rms:>12.4f} {Vc_peak:>12.4f}")
print(f"  {'-'*36}")
print(f"  {'3-phase avg RMS':<10} {np.mean([Va_rms,Vb_rms,Vc_rms]):>12.4f}")
print(f"  {'3-phase avg Peak':<10} {np.mean([Va_peak,Vb_peak,Vc_peak]):>12.4f}")
print(f"\n  Note: values are likely in per-unit (pu)")
print(f"  If peak ≈ 1.0 pu → base voltage needed to convert to volts")

"""## **Saving a figure to your Google Drive**


"""

# Saving a figure
"""plt.savefig(FIGURES_PATH + 'dwt_bands.png', dpi=150, bbox_inches='tight')

# Saving a model (we will do this in Phase D)
import joblib
joblib.dump(model, MODELS_PATH + 'mlp_islanding.pkl')
```

Because these paths point to your Google Drive, the files are saved permanently and survive session resets.

---

## Common Issues and Fixes
```
Issue: "Mounted at /content/drive" but files not found
Fix:   Print os.listdir('/content/drive/MyDrive/') to see
       exactly what folder names exist — check capitalisation

Issue: Drive mount popup does not appear
Fix:   Runtime → Disconnect and delete runtime → try again

Issue: Session resets and everything is gone
Fix:   Only the /content/ local files are lost
       Your Drive files are always safe
       Just re-run Phase 0 cells top to bottom

"""

"""**#  PHASE A — DATA PREPARATION**
- Load all 19 files, tag each with event class, split 60/20/20 at recording level BEFORE any windowing or feature extraction

**#  CLASS DEFINITIONS:**
- Class 0 → Normal / grid-connected   (pre-event ALL files) + all load_switching and capacitor switching events
- Class 1 → Islanding
- Class 2 → Line fault

**# DATASET DEFINITIONS**
- Each entry: filename → (description, post_event_class)
"""

DATASETS = {
    'V_zone1_numeric.mat'  : ('Islanding Zone 1',        1),
    'V_zone2_numeric.mat'  : ('Islanding Zone 2',        1),
    'V_zone3_numeric.mat'  : ('Islanding Zone 3',        1),
    'V_zone4_numeric.mat'  : ('Islanding Zone 4',        1),
    'V_zone12_numeric.mat' : ('Islanding Zone 1+2',      1),
    'Vb1LG_numeric.mat'    : ('SLG Fault Bus 1',         2),
    'Vb1LLG_numeric.mat'   : ('LLG Fault Bus 1',         2),
    'Vb1LLLG_numeric.mat'  : ('LLLG Fault Bus 1',        2),
    'Vb2LG_numeric.mat'    : ('SLG Fault Bus 2',         2),
    'Vb2LLG_numeric.mat'   : ('LLG Fault Bus 2',         2),
    'Vb2LLLG_numeric.mat'  : ('LLLG Fault Bus 2',        2),
    'Vb1nilsw_numeric.mat' : ('Load Switching Bus 1',    0),
    'Vb3nilsw_numeric.mat' : ('Load Switching Bus 3',    0),
    'Vb4nilsw_numeric.mat' : ('Load Switching Bus 4',    0),
    'Vb1nicw_numeric.mat'  : ('Cap Switching Bus 1',     0),
    'Vb2nicw_numeric.mat'  : ('Cap Switching Bus 2',     0),
    'Vb3nicw_numeric.mat'  : ('Cap Switching Bus 3',     0),
    'Vb4nicw_numeric.mat'  : ('Cap Switching Bus 4',     0),
    'Vb6nicw_numeric.mat'  : ('Cap Switching Bus 6',     0),
}

CLASS_NAMES = {0: 'Non-islanding', 1: 'Islanding', 2: 'Line fault'}

NON_PU_FILES = {
    'V_zone4_numeric.mat', 'Vb2LG_numeric.mat', 'Vb2LLG_numeric.mat',
    'Vb2LLLG_numeric.mat', 'Vb2nicw_numeric.mat',
}

PHASE_BASE_VOLTAGE = 20323.67

FS          = 3840
WINDOW_SIZE = 64
EVENT_CYCLE = int(0.5 * FS) // WINDOW_SIZE
PRE_CYCLES  = EVENT_CYCLE - 1
POST_CYCLES = (2881 // WINDOW_SIZE) - EVENT_CYCLE + 1

def normalise_recording(recording, filename):
    if filename not in NON_PU_FILES:
        return recording
    normalised = recording.copy()
    for col in [1, 2, 3]:
        normalised[:, col] = recording[:, col] / PHASE_BASE_VOLTAGE
    return normalised

print("=" * 65)
print("PHASE A - DATA PREPARATION (3-class)")
print("  Class 0: Non-islanding | Class 1: Islanding | Class 2: Line fault")
print("  Cycle 30 INCLUDED in post-event (event aligns with cycle 30 start)")
print("  Pre-event: cycles 1-29 (29) | Post-event: cycles 30-45 (16)")
print("=" * 65)
print()

all_recordings    = []
all_sources       = []
all_event_classes = []
total_loaded      = 0
missing_files     = []
normalised_count  = 0

print("Loading all 19 dataset files...")
print("-" * 65)

for filename, (description, post_class) in DATASETS.items():
    filepath = DATA_PATH + filename
    if not os.path.exists(filepath):
        print(f"  NOT FOUND : {filename}")
        missing_files.append(filename)
        continue
    mat      = scipy.io.loadmat(filepath, squeeze_me=True, struct_as_record=False)
    cell_out = mat['cell_out']
    n_recs   = len(cell_out)
    needs_norm = filename in NON_PU_FILES
    for i in range(n_recs):
        recording = np.array(cell_out[i], dtype=float)
        recording = normalise_recording(recording, filename)
        all_recordings.append(recording)
        all_sources.append(filename)
        all_event_classes.append(post_class)
    norm_tag = ' [normalised -> pu]' if needs_norm else ' [already pu]'
    print(f"  OK {filename:<30} {n_recs:>4} recs  class {post_class}  {norm_tag}")
    total_loaded += n_recs
    if needs_norm:
        normalised_count += n_recs

all_recordings    = np.array(all_recordings,    dtype=object)
all_sources       = np.array(all_sources)
all_event_classes = np.array(all_event_classes, dtype=np.int32)

print("-" * 65)
print(f"  Total recordings loaded    : {total_loaded}")
print(f"  Recordings normalised to pu: {normalised_count}")
print(f"  Recordings already in pu   : {total_loaded - normalised_count}")
if missing_files:
    print(f"  WARNING Missing files: {missing_files}")

print()
print("=" * 65)
print("STEP 2 - NORMALISATION VERIFICATION")
print("=" * 65)
print(f"  {'FILE':<30} {'MIN (pu)':>10} {'MAX (pu)':>10}  STATUS")
print("-" * 65)
all_ok = True
for filename in DATASETS.keys():
    file_mask = all_sources == filename
    if not np.any(file_mask):
        continue
    sample = all_recordings[file_mask][0]
    v_min  = min(np.min(sample[:, col]) for col in [1, 2, 3])
    v_max  = max(np.max(sample[:, col]) for col in [1, 2, 3])
    status = 'ok' if abs(v_max) <= 3.0 else 'WARNING out of range'
    if abs(v_max) > 3.0:
        all_ok = False
    print(f"  {filename:<30} {v_min:>10.4f} {v_max:>10.4f}  {status}")
print("-" * 65)
print("  All files confirmed in per unit range" if all_ok else
      "  WARNING Some files out of range")

print()
print("=" * 65)
print("STEP 3 - RECORDINGS PER POST-EVENT CLASS")
print("=" * 65)
for cls in range(0, 3):
    count = np.sum(all_event_classes == cls)
    print(f"  Class {cls} ({CLASS_NAMES[cls]:<20}): {count:>5} recordings")
print(f"  {'TOTAL':<27}: {len(all_recordings):>5} recordings")

print()
print("=" * 65)
print("STEP 4 - STRATIFIED TRAIN / VAL / TEST SPLIT (60/20/20)")
print("=" * 65)

indices = np.arange(len(all_recordings))
train_idx, temp_idx = train_test_split(
    indices, test_size=0.40, random_state=42,
    shuffle=True, stratify=all_event_classes)
val_idx, test_idx = train_test_split(
    temp_idx, test_size=0.50, random_state=42,
    shuffle=True, stratify=all_event_classes[temp_idx])

train_recordings    = all_recordings[train_idx]
val_recordings      = all_recordings[val_idx]
test_recordings     = all_recordings[test_idx]
train_sources       = all_sources[train_idx]
val_sources         = all_sources[val_idx]
test_sources        = all_sources[test_idx]
train_event_classes = all_event_classes[train_idx]
val_event_classes   = all_event_classes[val_idx]
test_event_classes  = all_event_classes[test_idx]

print(f"  Total recordings  : {len(all_recordings)}")
print(f"  Training set      : {len(train_recordings)} recordings (60%)")
print(f"  Validation set    : {len(val_recordings)}  recordings (20%)")
print(f"  Test set          : {len(test_recordings)}  recordings (20%)")
print()

for split_name, event_classes in [
    ('TRAINING',   train_event_classes),
    ('VALIDATION', val_event_classes),
    ('TEST',       test_event_classes),
]:
    print(f"  {split_name} - recordings per class:")
    for cls in range(0, 3):
        count = np.sum(event_classes == cls)
        print(f"    Class {cls} ({CLASS_NAMES[cls]:<20}): {count:>4} recordings")
    print()

print("=" * 65)
print("STEP 5 - CYCLE-LEVEL PREVIEW (after Phase B windowing)")
print("=" * 65)
print(f"  Pre-event  cycles : 1-29  ({PRE_CYCLES} cycles)  -> class 0")
print(f"  Post-event cycles : 30-45 ({POST_CYCLES} cycles) -> post-event class")
print(f"  Cycle 30 INCLUDED - no transition cycle discarded")
print()

for split_name, recordings, event_classes in [
    ('TRAINING',   train_recordings,   train_event_classes),
    ('VALIDATION', val_recordings,     val_event_classes),
    ('TEST',       test_recordings,    test_event_classes),
]:
    n_recs           = len(recordings)
    pre_event_cycles = n_recs * PRE_CYCLES
    post_cls0_cycles = int(np.sum(event_classes == 0)) * POST_CYCLES
    total_cls0       = pre_event_cycles + post_cls0_cycles
    print(f"  {split_name} SET ({n_recs} recordings):")
    print(f"    Class 0 ({CLASS_NAMES[0]:<17}): {total_cls0:>7,} cycles"
          f"  [{pre_event_cycles:,} pre-event + {post_cls0_cycles:,} post load/cap]")
    for cls in range(1, 3):
        n_cls = int(np.sum(event_classes == cls))
        n_cyc = n_cls * POST_CYCLES
        print(f"    Class {cls} ({CLASS_NAMES[cls]:<17}): "
              f"{n_cyc:>7,} cycles  [{n_cls} recs x {POST_CYCLES}]")
    total = total_cls0 + sum(
        int(np.sum(event_classes == c)) * POST_CYCLES for c in range(1, 3))
    print(f"    Total                       : {total:>7,} cycles")
    print()

print("=" * 65)
print("STEP 6 - BALANCING STRATEGY PREVIEW (training set only)")
print("=" * 65)

train_pre_event  = len(train_recordings) * PRE_CYCLES
train_post_cls0  = int(np.sum(train_event_classes == 0)) * POST_CYCLES
train_cls0_total = train_pre_event + train_post_cls0
train_cls1       = int(np.sum(train_event_classes == 1)) * POST_CYCLES
train_cls2       = int(np.sum(train_event_classes == 2)) * POST_CYCLES
target           = train_cls1

print(f"  Reference size -> class 1 (islanding): {target:,} cycles")
print()
print(f"  Class 0  {train_cls0_total:>8,} cycles -> undersample to {target:,}  "
      f"(remove {train_cls0_total - target:,})")
print(f"  Class 1  {train_cls1:>8,} cycles -> keep as is  (reference)")
print(f"  Class 2  {train_cls2:>8,} cycles -> keep as is  "
      f"(ratio to class 1: {target/max(train_cls2,1):.1f}:1)")
print()
print(f"  Balanced training total : {target + train_cls1 + train_cls2:,} cycles")
print()
print("  No augmentation needed - all 3 classes are sufficiently sized.")
print()
print("  Phase A complete - ready for Phase B (windowing)")

"""**#  PHASE B — CYCLE-BY-CYCLE WINDOWING**
- Slice each recording into 64-sample cycles and assign labels

**#  LABELLING LOGIC:**
- Pre-event  cycles (1–29)  → class 0  (normal, ALL files) + Load switching files + Cap switching files
- Transition cycle (30)     → DISCARD
- Post-event cycles (31–45) → post_event_class from Phase A
- Islanding files        → class 1
- Line fault files       → class 2
"""

# ================================================================
#  PHASE B - CYCLE-BY-CYCLE WINDOWING
#
#  Changes from original:
#    - Cycle 30 INCLUDED in post-event (no transition cycle discarded)
#    - Post-event cycles: 30-45 (16 cycles per recording)
#    - Pre-event cycles : 1-29  (29 cycles per recording)
#    - Total usable cycles per recording: 45
#    - CLASS_NAMES updated to 3-class structure
#    - Sanity check updated to expect 45 cycles per recording
# ================================================================

# -- WINDOWING PARAMETERS -----------------------------------------
FS           = 3840   # sampling rate (Hz)
WINDOW_SIZE  = 64     # samples per cycle (3840 / 60Hz = 64)
EVENT_SAMPLE = int(0.5 * FS)                # CB trips at t=0.5s = sample 1920
EVENT_CYCLE  = EVENT_SAMPLE // WINDOW_SIZE  # = 30 (0-indexed: 29)

# Cycle 30 is INCLUDED because the event starts at exactly sample 1920
# which is the start of cycle 30 (0-indexed: 29). Verified: Aligned = True.
# No transition cycle is discarded.

print("=" * 60)
print("PHASE B - CYCLE-BY-CYCLE WINDOWING")
print("=" * 60)
print(f"  Sampling rate    : {FS} Hz")
print(f"  Window size      : {WINDOW_SIZE} samples = 1 power cycle")
print(f"  Event at sample  : {EVENT_SAMPLE} (t = 0.5s)")
print(f"  Event at cycle   : {EVENT_CYCLE} (0-indexed: {EVENT_CYCLE - 1})")
print(f"  Pre-event cycles : 0 to {EVENT_CYCLE - 2} (0-indexed) -> class 0")
print(f"  Post-event cycles: {EVENT_CYCLE - 1} to end (0-indexed) -> post-event class")
print(f"  Cycle 30 INCLUDED - no transition cycle discarded")
print(f"  Cycles per recording: 45 (29 pre + 16 post)")
print()

# -- WINDOWING FUNCTION -------------------------------------------
def slice_recordings_into_cycles(recordings, event_classes, split_name):
    """
    Slices each full 2881-sample recording into 64-sample cycles
    and assigns the correct class label to each cycle.

    Parameters:
        recordings    : array of 2881x4 recordings
        event_classes : array of post-event class labels
                        (one per recording, from Phase A)
        split_name    : string label for printing ('Training' etc.)

    Returns:
        cycles : np.array of shape (N, 3, 64)
                 N = total cycles across all recordings
                 3 = three phases (Va, Vb, Vc)
                 64 = samples per cycle

        labels : np.array of shape (N,)
                 class label for each cycle (0, 1, or 2)

    Cycle assignment:
        cycle_idx < EVENT_CYCLE - 1  -> class 0 (pre-event, normal)
        cycle_idx >= EVENT_CYCLE - 1 -> post_class (post-event)
        No cycle is discarded — cycle 30 (0-indexed: 29) is clean.
    """

    all_cycles = []
    all_labels = []

    n_recordings = len(recordings)

    for rec_idx in range(n_recordings):

        recording  = recordings[rec_idx]     # shape: (2881, 4)
        post_class = event_classes[rec_idx]  # class for post-event cycles

        # Extract three phase voltages (skip column 0 = time)
        Va = recording[:, 1]
        Vb = recording[:, 2]
        Vc = recording[:, 3]

        # Total number of complete 64-sample cycles
        n_cycles = len(Va) // WINDOW_SIZE    # = 45 cycles

        for cycle_idx in range(n_cycles):

            # -- Extract 64-sample window -------------------------
            start = cycle_idx * WINDOW_SIZE
            end   = start + WINDOW_SIZE

            window_Va = Va[start:end]   # shape: (64,)
            window_Vb = Vb[start:end]   # shape: (64,)
            window_Vc = Vc[start:end]   # shape: (64,)

            # Stack three phases -> shape: (3, 64)
            window = np.stack([window_Va, window_Vb, window_Vc], axis=0)

            # -- Assign label -------------------------------------
            # EVENT_CYCLE - 1 = 29 (0-indexed) = cycle 30 (1-indexed)
            # Cycles 0-28 (0-indexed) = pre-event  -> class 0
            # Cycles 29-44 (0-indexed) = post-event -> post_class
            if cycle_idx < EVENT_CYCLE - 1:
                label = 0            # pre-event -> class 0 (non-islanding)
            else:
                label = post_class   # post-event -> class from Phase A

            all_cycles.append(window)
            all_labels.append(label)

    cycles = np.array(all_cycles, dtype=np.float32)   # (N, 3, 64)
    labels = np.array(all_labels, dtype=np.int32)      # (N,)

    return cycles, labels


# -- APPLY TO ALL THREE SETS --------------------------------------
print("Slicing recordings into cycles...")
print()

X_train_cycles, y_train = slice_recordings_into_cycles(
    train_recordings, train_event_classes, 'Training')

X_val_cycles, y_val = slice_recordings_into_cycles(
    val_recordings, val_event_classes, 'Validation')

X_test_cycles, y_test = slice_recordings_into_cycles(
    test_recordings, test_event_classes, 'Test')


# -- RESULTS ------------------------------------------------------
CLASS_NAMES = {
    0: 'Non-islanding',
    1: 'Islanding',
    2: 'Line fault',
}

print("=" * 60)
print("WINDOWING RESULTS")
print("=" * 60)

for split_name, cycles, labels in [
    ('TRAINING',   X_train_cycles, y_train),
    ('VALIDATION', X_val_cycles,   y_val),
    ('TEST',       X_test_cycles,  y_test),
]:
    print(f"\n  {split_name} SET:")
    print(f"    Array shape : {cycles.shape}  (cycles, phases, samples)")

    total = len(labels)
    for cls in range(3):
        count = np.sum(labels == cls)
        pct   = 100 * count / total
        bar   = '#' * int(pct / 2)
        print(f"    Class {cls} ({CLASS_NAMES[cls]:<16}): "
              f"{count:>7,}  ({pct:5.1f}%)  {bar}")

    print(f"    {'Total':<22}  : {total:>7,}")


# -- SANITY CHECKS ------------------------------------------------
print()
print("=" * 60)
print("SANITY CHECKS")
print("=" * 60)

# Check 1: every recording contributes exactly 45 cycles
# (29 pre-event + 16 post-event, no cycle discarded)
expected_train = len(train_recordings) * 45
expected_val   = len(val_recordings)   * 45
expected_test  = len(test_recordings)  * 45

print(f"  Expected cycles per recording : 45 (29 pre + 16 post)")
print()
print(f"  Expected training cycles : {expected_train:,}")
print(f"  Actual  training cycles  : {len(y_train):,}  "
      + ("OK" if len(y_train) == expected_train else "MISMATCH"))

print(f"  Expected val cycles      : {expected_val:,}")
print(f"  Actual  val cycles       : {len(y_val):,}  "
      + ("OK" if len(y_val) == expected_val else "MISMATCH"))

print(f"  Expected test cycles     : {expected_test:,}")
print(f"  Actual  test cycles      : {len(y_test):,}  "
      + ("OK" if len(y_test) == expected_test else "MISMATCH"))

# Check 2: window values should be in reasonable voltage range
v_min = X_train_cycles.min()
v_max = X_train_cycles.max()
print(f"\n  Voltage range in training windows:")
print(f"    Min : {v_min:.4f} pu")
print(f"    Max : {v_max:.4f} pu")
print(f"    Expected : roughly -2.0 to +2.0 pu  "
      + ("OK" if -3.0 < v_min and v_max < 3.0 else "WARNING check values"))

# Check 3: class 0 should be the largest class in all sets
for split_name, labels in [
    ('Training',   y_train),
    ('Validation', y_val),
    ('Test',       y_test),
]:
    cls0 = np.sum(labels == 0)
    cls1 = np.sum(labels == 1)
    ok   = cls0 > cls1
    print(f"\n  {split_name}: class 0 > class 1  "
          f"({cls0:,} > {cls1:,})  " + ("OK" if ok else "WARNING"))

# Check 4: verify cycle 30 (0-indexed: 29) is assigned to post-event class
# Sample first islanding recording and check label at cycle index 29
islanding_mask = train_event_classes == 1
if np.any(islanding_mask):
    sample_rec    = train_recordings[islanding_mask][0]
    sample_class  = train_event_classes[islanding_mask][0]
    # cycle 29 (0-indexed) should have label = 1 (islanding)
    # find its position in y_train
    rec_global_idx = np.where(islanding_mask)[0][0]
    cycle_offset   = rec_global_idx * 45 + 29   # 45 cycles per rec, cycle 29
    label_at_30    = y_train[cycle_offset] if cycle_offset < len(y_train) else -1
    print(f"\n  Cycle 30 label check (first islanding recording):")
    print(f"    Label at cycle index 29 (0-indexed): {label_at_30}  "
          + ("OK (post-event)" if label_at_30 == 1 else "WARNING"))

print()
print("  Phase B complete - ready for Phase C (DWT features)")

"""**#  LABEL PREVIEW — what the cycle-level labels will look like after Phase B windowing**
- CYCLE VISUALISATION
- Shows sample cycles from each of the 5 classes to confirm windowing and labelling are correct
"""

# ═══════════════════════════════════════════════════════════════════
#  NORMALISATION VERIFICATION — VISUAL CHECK
#  Plots the full 0.75s recording for each of the 5 non-pu files
#  before and after normalisation to confirm correctness
#
#  Files checked:
#    V_zone4_numeric.mat
#    Vb2LG_numeric.mat
#    Vb2LLG_numeric.mat
#    Vb2LLLG_numeric.mat
#    Vb2nicw_numeric.mat
#
#  Normalisation method:
#    Divide by fixed physical base voltage (20,323.67 V)
#    Derived from: actual_RMS (V_zone4) / reference_RMS (V_zone1)
#    = 14,527.72 V / 0.7148 pu = 20,323.67 V
#    Expected peak after normalisation : ≈ ±1.011 pu
#    Expected RMS  after normalisation : ≈  0.7148 pu
# ═══════════════════════════════════════════════════════════════════

# ── PHYSICAL BASE VOLTAGE ─────────────────────────────────────────
# Derived from V_zone4 actual RMS vs V_zone1 reference RMS
PHASE_BASE_VOLTAGE = 20323.67   # Volts

NON_PU_FILES = [
    'V_zone4_numeric.mat',
    'Vb2LG_numeric.mat',
    'Vb2LLG_numeric.mat',
    'Vb2LLLG_numeric.mat',
    'Vb2nicw_numeric.mat',
]

NON_PU_SET = set(NON_PU_FILES)

FILE_TITLES = {
    'V_zone4_numeric.mat'  : 'Islanding Zone 4',
    'Vb2LG_numeric.mat'    : 'SLG Fault Bus 2',
    'Vb2LLG_numeric.mat'   : 'LLG Fault Bus 2',
    'Vb2LLLG_numeric.mat'  : 'LLLG Fault Bus 2',
    'Vb2nicw_numeric.mat'  : 'Capacitor Switching Bus 2',
}

PHASE_COLORS = ['steelblue', 'darkorange', 'forestgreen']
PHASE_LABELS = ['Va', 'Vb', 'Vc']
PRE_EVENT_SAMPLES = 29 * 64   # 1856 samples


def normalise_recording(recording, filename):
    """
    Normalise a recording to per unit.
    Non-PU files: divide by fixed physical base voltage (20,323.67 V).
    Already-PU files: returned unchanged.
    """
    if filename not in NON_PU_SET:
        return recording  # already in PU, no change
    normalised = recording.copy()
    for col in [1, 2, 3]:
        normalised[:, col] = recording[:, col] / PHASE_BASE_VOLTAGE
    return normalised


# ── FIGURE 1: BEFORE vs AFTER NORMALISATION (full recording) ──────
print("Generating Figure 1: Before vs After Normalisation...")

fig1, axes1 = plt.subplots(5, 2, figsize=(18, 20))
fig1.suptitle('Normalisation Verification — Before vs After\n'
              'Left: Raw (actual volts)  |  Right: Normalised (per unit)\n'
              f'Base voltage = {PHASE_BASE_VOLTAGE:,.2f} V  |  '
              f'Expected peak ≈ ±1.011 pu',
              fontsize=13, fontweight='bold')

for row, filename in enumerate(NON_PU_FILES):
    filepath = DATA_PATH + filename

    mat      = scipy.io.loadmat(filepath, squeeze_me=True,
                                struct_as_record=False)
    rec_raw  = np.array(mat['cell_out'][0], dtype=float)
    rec_norm = normalise_recording(rec_raw, filename)

    time = rec_raw[:, 0]

    ax_raw  = axes1[row, 0]
    ax_norm = axes1[row, 1]

    # Plot raw
    for col, (color, label) in enumerate(
            zip(PHASE_COLORS, PHASE_LABELS), start=1):
        ax_raw.plot(time, rec_raw[:, col],
                    color=color, linewidth=0.7, label=label)

    ax_raw.axvline(0.5, color='red', linestyle='--',
                   linewidth=1.0, label='Event t=0.5s')
    ax_raw.set_title(f'{FILE_TITLES[filename]} — RAW (volts)',
                     fontsize=9, fontweight='bold')
    ax_raw.set_ylabel('Voltage (V)', fontsize=8)
    ax_raw.legend(fontsize=7, loc='upper right')
    ax_raw.grid(alpha=0.3)

    # Plot normalised
    for col, (color, label) in enumerate(
            zip(PHASE_COLORS, PHASE_LABELS), start=1):
        ax_norm.plot(time, rec_norm[:, col],
                     color=color, linewidth=0.7, label=label)

    ax_norm.axvline(0.5, color='red', linestyle='--',
                    linewidth=1.0, label='Event t=0.5s')
    ax_norm.axhline(1.011, color='gray', linestyle=':',
                    linewidth=0.8, label='≈1.011 pu (expected peak)')
    ax_norm.axhline(-1.011, color='gray', linestyle=':',
                    linewidth=0.8)
    ax_norm.set_title(f'{FILE_TITLES[filename]} — NORMALISED (pu)',
                      fontsize=9, fontweight='bold', color='darkgreen')
    ax_norm.set_ylabel('Voltage (pu)', fontsize=8)
    ax_norm.legend(fontsize=7, loc='upper right')
    ax_norm.grid(alpha=0.3)
    ax_norm.set_ylim(-3.0, 3.0)

for ax in axes1[-1]:
    ax.set_xlabel('Time (s)', fontsize=9)

plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.savefig(FIGURES_PATH + 'normalisation_before_after.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("  ✓ Figure 1 saved: normalisation_before_after.png")


# ── FIGURE 2: ALL 19 FILES SIDE BY SIDE (normalised only) ─────────
print("\nGenerating Figure 2: All 19 files normalised (Va only)...")

ALL_FILES = {
    'V_zone1_numeric.mat'  : ('Islanding Z1',   '#F44336'),
    'V_zone2_numeric.mat'  : ('Islanding Z2',   '#F44336'),
    'V_zone3_numeric.mat'  : ('Islanding Z3',   '#F44336'),
    'V_zone4_numeric.mat'  : ('Islanding Z4',   '#F44336'),
    'V_zone12_numeric.mat' : ('Islanding Z1+2', '#F44336'),
    'Vb1LG_numeric.mat'    : ('SLG Bus1',       '#FF9800'),
    'Vb1LLG_numeric.mat'   : ('LLG Bus1',       '#FF9800'),
    'Vb1LLLG_numeric.mat'  : ('LLLG Bus1',      '#FF9800'),
    'Vb2LG_numeric.mat'    : ('SLG Bus2',       '#FF9800'),
    'Vb2LLG_numeric.mat'   : ('LLG Bus2',       '#FF9800'),
    'Vb2LLLG_numeric.mat'  : ('LLLG Bus2',      '#FF9800'),
    'Vb1nilsw_numeric.mat' : ('Load Sw Bus1',   '#4CAF50'),
    'Vb3nilsw_numeric.mat' : ('Load Sw Bus3',   '#4CAF50'),
    'Vb4nilsw_numeric.mat' : ('Load Sw Bus4',   '#4CAF50'),
    'Vb1nicw_numeric.mat'  : ('Cap Sw Bus1',    '#9C27B0'),
    'Vb2nicw_numeric.mat'  : ('Cap Sw Bus2',    '#9C27B0'),
    'Vb3nicw_numeric.mat'  : ('Cap Sw Bus3',    '#9C27B0'),
    'Vb4nicw_numeric.mat'  : ('Cap Sw Bus4',    '#9C27B0'),
    'Vb6nicw_numeric.mat'  : ('Cap Sw Bus6',    '#9C27B0'),
}

fig2, axes2 = plt.subplots(4, 5, figsize=(22, 14), sharex=True)
fig2.suptitle('All 19 Files — Va Phase After Normalisation\n'
              'Red=Islanding  Orange=Fault  Green=Load Sw  Purple=Cap Sw\n'
              f'Non-PU files divided by {PHASE_BASE_VOLTAGE:,.2f} V',
              fontsize=12, fontweight='bold')

axes_flat = axes2.flatten()

for idx, (filename, (title, color)) in enumerate(ALL_FILES.items()):
    ax       = axes_flat[idx]
    filepath = DATA_PATH + filename

    mat = scipy.io.loadmat(filepath, squeeze_me=True,
                           struct_as_record=False)
    rec = np.array(mat['cell_out'][0], dtype=float)
    rec = normalise_recording(rec, filename)

    time = rec[:, 0]
    Va   = rec[:, 1]

    ax.plot(time, Va, color=color, linewidth=0.6)
    ax.axvline(0.5, color='black', linestyle='--',
               linewidth=0.8, alpha=0.7)
    ax.axhline(0, color='gray', linewidth=0.3)
    ax.set_title(title, fontsize=8, fontweight='bold', color=color)
    ax.set_ylim(-3.0, 3.0)
    ax.grid(alpha=0.2)
    ax.tick_params(labelsize=6)

    if idx % 5 == 0:
        ax.set_ylabel('Va (pu)', fontsize=7)
    if idx >= 15:
        ax.set_xlabel('Time (s)', fontsize=7)

axes_flat[19].set_visible(False)

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.savefig(FIGURES_PATH + 'all_19_files_normalised.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("  ✓ Figure 2 saved: all_19_files_normalised.png")


# ── FIGURE 3: ZOOM INTO EVENT WINDOW (normalised) ─────────────────
print("\nGenerating Figure 3: Zoom into event window (normalised)...")

fig3, axes3 = plt.subplots(5, 1, figsize=(14, 18), sharex=True)
fig3.suptitle('Zoom Into Event Window (t = 0.45s to 0.60s)\n'
              'Normalised to per unit — all 3 phases',
              fontsize=12, fontweight='bold')

for row, filename in enumerate(NON_PU_FILES):
    filepath = DATA_PATH + filename

    mat = scipy.io.loadmat(filepath, squeeze_me=True,
                           struct_as_record=False)
    rec = np.array(mat['cell_out'][0], dtype=float)
    rec = normalise_recording(rec, filename)

    time = rec[:, 0]
    mask = (time >= 0.45) & (time <= 0.60)

    ax = axes3[row]
    for col, (color, label) in enumerate(
            zip(PHASE_COLORS, PHASE_LABELS), start=1):
        ax.plot(time[mask], rec[mask, col],
                color=color, linewidth=1.0, label=label)

    ax.axvline(0.5, color='red', linestyle='--',
               linewidth=1.2, label='Event t=0.5s')
    ax.axvspan(0.5, 0.5 + 64/3840, alpha=0.15,
               color='red', label='Transition cycle')
    ax.set_title(f'{FILE_TITLES[filename]} — normalised',
                 fontsize=10, fontweight='bold')
    ax.set_ylabel('Voltage (pu)', fontsize=8)
    ax.legend(fontsize=7, loc='upper right')
    ax.grid(alpha=0.3)
    ax.set_ylim(-3.0, 3.0)

axes3[-1].set_xlabel('Time (s)', fontsize=9)
plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.savefig(FIGURES_PATH + 'normalised_event_zoom.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("  ✓ Figure 3 saved: normalised_event_zoom.png")


# ── VOLTAGE RANGE SUMMARY ─────────────────────────────────────────
print()
print("=" * 70)
print("VOLTAGE RANGE SUMMARY — ALL 19 FILES AFTER NORMALISATION")
print(f"Non-PU files divided by fixed base: {PHASE_BASE_VOLTAGE:,.2f} V")
print("=" * 70)
print(f"  {'FILE':<30} {'Va min':>8} {'Va max':>8} {'Va RMS':>8}  STATUS")
print("-" * 70)

for filename in ALL_FILES.keys():
    filepath = DATA_PATH + filename
    mat      = scipy.io.loadmat(filepath, squeeze_me=True,
                                struct_as_record=False)
    rec      = np.array(mat['cell_out'][0], dtype=float)
    rec      = normalise_recording(rec, filename)

    Va      = rec[:, 1]
    va_min  = np.min(Va)
    va_max  = np.max(Va)
    va_rms  = np.sqrt(np.mean(Va[:PRE_EVENT_SAMPLES] ** 2))

    tag    = ' ← normalised' if filename in NON_PU_SET else ''
    status = '✓ ok' if abs(va_max) <= 3.0 else '⚠ check'
    print(f"  {filename:<30} {va_min:>8.4f} {va_max:>8.4f} {va_rms:>8.4f}  "
          f"{status}{tag}")

print("=" * 70)
print("  Expected for normalised files : peak ≈ ±1.011 pu, RMS ≈ 0.7148 pu")
print("  Expected for already-PU files : peak ≈ ±1.234 pu, RMS ≈ 0.7148 pu")
print("  ✓ Normalisation verification complete")

plt.savefig(FIGURES_PATH + 'normalisation_before_after.png', dpi=150, bbox_inches='tight')
plt.savefig(FIGURES_PATH + 'all_19_files_normalised.png', dpi=150, bbox_inches='tight')
plt.savefig(FIGURES_PATH + 'normalised_event_zoom.png', dpi=150, bbox_inches='tight')

print("X_train_cycles:", X_train_cycles.shape)
print("y_train:", y_train.shape)
print("X_val_cycles:", X_val_cycles.shape)
print("y_val:", y_val.shape)
print("X_test_cycles:", X_test_cycles.shape)
print("y_test:", y_test.shape)

"""CNN Model

```
# This is formatted as code
```


"""



# Colour scheme per phase
PHASE_COLORS = ['steelblue', 'darkorange', 'forestgreen']
PHASE_LABELS = ['Va', 'Vb', 'Vc']

CLASS_NAMES = {
    0: 'Non-islanding',
    1: 'Islanding',
    2: 'Line Fault',
}

CLASS_COLORS = {
    0: '#2196F3',
    1: '#F44336',
    2: '#FF9800',
}

# ================================================================
#  FIGURE 1 - ONE CYCLE PER CLASS (3 phases overlaid)
# ================================================================
fig1, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)
fig1.suptitle(
    'Typical 64-Sample Cycle - One Per Class'
    ' (3 phases overlaid, training set)',
    fontsize=13, fontweight='bold', y=0.98)

for cls in range(3):
    ax         = axes[cls]
    cls_mask   = y_train == cls
    cls_cycles = X_train_cycles[cls_mask]
    if len(cls_cycles) == 0:
        ax.set_title('Class ' + str(cls) + ' - no cycles found', fontsize=10)
        continue
    cycle  = cls_cycles[0]
    x_axis = np.arange(64)
    for phase_idx, (color, label) in enumerate(zip(PHASE_COLORS, PHASE_LABELS)):
        ax.plot(x_axis, cycle[phase_idx, :], color=color, linewidth=1.2, label=label)
    ax.set_title('Class ' + str(cls) + ' - ' + CLASS_NAMES[cls],
                 fontsize=10, fontweight='bold', color=CLASS_COLORS[cls])
    ax.set_ylabel('Voltage (pu)', fontsize=8)
    ax.legend(fontsize=8, loc='upper right')
    ax.grid(alpha=0.3)
    ax.axhline(0, color='gray', linewidth=0.5, linestyle='--')
    ax.set_ylim(-3.5, 3.5)

axes[-1].set_xlabel('Sample number within cycle (0-63)', fontsize=9)
plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.savefig(FIGURES_PATH + 'cycles_one_per_class.png', dpi=150, bbox_inches='tight')
plt.show()
print('Figure 1 saved: cycles_one_per_class.png')


# ================================================================
#  FIGURE 2 - PRE vs POST EVENT COMPARISON
# ================================================================
fig2, axes2 = plt.subplots(2, 2, figsize=(16, 8))
fig2.suptitle(
    'Pre-Event (Class 0) vs Post-Event Comparison'
    ' - Same recording, cycle before and after event',
    fontsize=13, fontweight='bold')

event_classes_plot = [1, 2]

for row, cls in enumerate(event_classes_plot):
    ax_pre  = axes2[row, 0]
    ax_post = axes2[row, 1]
    cls_mask   = y_train == cls
    pre_mask   = y_train == 0
    cls_cycles = X_train_cycles[cls_mask]
    pre_cycles = X_train_cycles[pre_mask]
    if len(cls_cycles) == 0:
        continue
    pre_cycle  = pre_cycles[50]
    # Find a cycle from a LLLG or LLG file specifically
    lllg_mask = np.array([train_sources[i // 45] in
                      ['Vb1LLLG_numeric.mat', 'Vb2LLLG_numeric.mat']
                      for i in np.where(y_train == 2)[0]])
    post_cycle = X_train_cycles[y_train == 2][lllg_mask][0]
    x_axis     = np.arange(64)
    for phase_idx, (color, label) in enumerate(zip(PHASE_COLORS, PHASE_LABELS)):
        ax_pre.plot(x_axis, pre_cycle[phase_idx, :],
                    color=color, linewidth=1.2, label=label)
    ax_pre.set_title('Class 0 - Non-islanding (pre-event, before ' + CLASS_NAMES[cls] + ')',
                     fontsize=9, fontweight='bold', color='#2196F3')
    ax_pre.set_ylabel('Voltage (pu)', fontsize=8)
    ax_pre.legend(fontsize=7, loc='upper right')
    ax_pre.grid(alpha=0.3)
    ax_pre.axhline(0, color='gray', linewidth=0.5, linestyle='--')
    ax_pre.set_ylim(-3.5, 3.5)
    for phase_idx, (color, label) in enumerate(zip(PHASE_COLORS, PHASE_LABELS)):
        ax_post.plot(x_axis, post_cycle[phase_idx, :],
                     color=color, linewidth=1.2, label=label)
    ax_post.set_title('Class ' + str(cls) + ' - ' + CLASS_NAMES[cls] + ' (post-event cycle)',
                      fontsize=9, fontweight='bold', color=CLASS_COLORS[cls])
    ax_post.set_ylabel('Voltage (pu)', fontsize=8)
    ax_post.legend(fontsize=7, loc='upper right')
    ax_post.grid(alpha=0.3)
    ax_post.axhline(0, color='gray', linewidth=0.5, linestyle='--')
    ax_post.set_ylim(-3.5, 3.5)

for ax in axes2[-1]:
    ax.set_xlabel('Sample number (0-63)', fontsize=9)
plt.tight_layout()
plt.savefig(FIGURES_PATH + 'pre_vs_post_event.png', dpi=150, bbox_inches='tight')
plt.show()
print('Figure 2 saved: pre_vs_post_event.png')


# ================================================================
#  FIGURE 3 - CYCLE SEQUENCE AROUND THE EVENT
#  Cycles 27-29 (pre) | Cycles 30-32 (post)
#  Cycle 30 INCLUDED as onset cycle
# ================================================================
fig3, axes3 = plt.subplots(2, 6, figsize=(20, 7))
fig3.suptitle(
    'Cycle Sequence Around the Event (Va only)'
    '  |  Cycles 27-29: pre-event (blue)'
    '  |  Cycles 30-32: post-event (class colour)'
    '  |  Cycle 30 = onset (thicker line)',
    fontsize=10, fontweight='bold')

col_titles = ['Cycle 27 (pre)', 'Cycle 28 (pre)', 'Cycle 29 (pre)',
              'Cycle 30 (onset)', 'Cycle 31 (post)', 'Cycle 32 (post)']
WINDOW_SIZE = 64

for row, cls in enumerate([1, 2]):
    cls_rec_mask = train_event_classes == cls
    cls_recs     = train_recordings[cls_rec_mask]
    if len(cls_recs) == 0:
        continue
    rec    = cls_recs[0]
    Va     = rec[:, 1]
    cycle_numbers = [27, 28, 29, 30, 31, 32]
    for col, cyc_num in enumerate(cycle_numbers):
        ax      = axes3[row, col]
        cyc_idx = cyc_num - 1
        start   = cyc_idx * WINDOW_SIZE
        end     = start + WINDOW_SIZE
        if end > len(Va):
            ax.set_visible(False)
            continue
        window = Va[start:end]
        x_axis = np.arange(WINDOW_SIZE)
        if cyc_num <= 29:
            color = CLASS_COLORS[0]
            lw    = 1.0
        elif cyc_num == 30:
            color = '#B71C1C' if cls == 1 else '#E65100'
            lw    = 1.8
        else:
            color = CLASS_COLORS[cls]
            lw    = 1.0
        ax.plot(x_axis, window, color=color, linewidth=lw)
        ax.axhline(0, color='gray', linewidth=0.4, linestyle='--')
        ax.set_ylim(-3.5, 3.5)
        ax.grid(alpha=0.25)
        ax.tick_params(labelsize=6)
        if col == 0:
            ax.set_ylabel('Class ' + str(cls) + ' ' + CLASS_NAMES[cls][:12],
                          fontsize=7, fontweight='bold', color=CLASS_COLORS[cls])
        if row == 0:
            ax.set_title(col_titles[col], fontsize=8, fontweight='bold')
        if row == 1:
            ax.set_xlabel('Samples', fontsize=6)
    axes3[row, 2].spines['right'].set_color('red')
    axes3[row, 2].spines['right'].set_linewidth(2)

plt.tight_layout()
plt.savefig(FIGURES_PATH + 'cycle_sequence.png', dpi=150, bbox_inches='tight')
plt.show()
print('Figure 3 saved: cycle_sequence.png')


# ================================================================
#  CYCLE STATISTICS SUMMARY
# ================================================================
print()
print('=' * 55)
print('CYCLE STATISTICS SUMMARY')
print('=' * 55)
for cls in range(3):
    cls_mask   = y_train == cls
    cls_cycles = X_train_cycles[cls_mask]
    if len(cls_cycles) == 0:
        continue
    all_vals = cls_cycles.flatten()
    print()
    print('  Class ' + str(cls) + ' - ' + CLASS_NAMES[cls] + ':')
    print('    Count  : ' + str(len(cls_cycles)) + ' cycles')
    print('    Min    : ' + str(round(float(np.min(all_vals)), 4)) + ' pu')
    print('    Max    : ' + str(round(float(np.max(all_vals)), 4)) + ' pu')
    print('    Mean   : ' + str(round(float(np.mean(all_vals)), 4)) + ' pu')
    print('    Std    : ' + str(round(float(np.std(all_vals)), 4)) + ' pu')
    print('    RMS    : ' + str(round(float(np.sqrt(np.mean(all_vals**2))), 4)) + ' pu')

print()
print('  Visualisation complete - ready for Phase C (DWT)')

"""**#  PHASE C - DOWNSAMPLING + DWT FEATURE EXTRACTION**

**Step 1**: Downsample class 0 in training cycles ONLY to match class 1 size before DWT extraction

**Step 2**: DWT feature extraction
- Wavelet : Sym4
- Level   : 2  (reduced from 3 due to 64-sample window)
- Bands   : cA2 (0-480Hz)   -> 16 coefficients
- cD2 (480-960Hz) -> 16 coefficients
- cD1 (960-1920Hz)-> 32 coefficients
- Stats   : 12 per band per phase
- Total   : 3 phases x 3 bands x 12 stats = 108 features


**WHY LEVEL 2 INSTEAD OF LEVEL 3:**
- At Level 3 with 64-sample windows, cA3 and cD3 only have 8 coefficients each — too few for reliable
- kurtosis, THD and SINAD estimation.
- Level 2 gives 16 coefficients minimum per band, making all 12 statistics statistically meaningful.

**Step 3**: Spearman feature selection (|rho| > 0.1)

**Step 4**: StandardScaler
- Fit on balanced training set only
- Transform all three sets

"""

import numpy as np
import pywt
from sklearn.preprocessing import StandardScaler
WAVELET    = 'sym4'
DWT_LEVEL  = 2
N_PHASES   = 3
N_BANDS    = 3
N_STATS    = 12
N_FEATURES = N_PHASES * N_BANDS * N_STATS   # 108

BAND_NAMES = ['cA2', 'cD2', 'cD1']
STAT_NAMES = ['mean', 'std', 'rms', 'peak',
              'crest_factor', 'impulse_factor', 'shape_factor',
              'clearance_factor', 'kurtosis', 'skewness',
              'thd', 'sinad']
CLASS_NAMES = {0: 'Non-islanding', 1: 'Islanding', 2: 'Line Fault'}


# ================================================================
#  HELPER FUNCTIONS
# ================================================================
def compute_thd(coeffs):
    x = np.asarray(coeffs, dtype=float)
    if len(x) < 2:
        return 0.0
    fft_vals = np.abs(np.fft.rfft(x))
    if len(fft_vals) < 2 or fft_vals[1] < 1e-10:
        return 0.0
    fundamental = fft_vals[1]
    harmonics   = fft_vals[2:]
    return float(np.sqrt(np.sum(harmonics ** 2)) / fundamental)


def compute_sinad(coeffs):
    x = np.asarray(coeffs, dtype=float)
    if len(x) < 2:
        return 0.0
    fft_vals     = np.abs(np.fft.rfft(x))
    total_power  = np.sum(fft_vals ** 2)
    if total_power < 1e-10:
        return 0.0
    fund_idx     = np.argmax(fft_vals[1:]) + 1
    signal_power = fft_vals[fund_idx] ** 2
    noise_power  = total_power - signal_power
    if noise_power < 1e-10:
        return float(signal_power / 1e-10)
    return float(signal_power / noise_power)


def extract_band_features(coeffs):
    x        = np.asarray(coeffs, dtype=float)
    xabs     = np.abs(x)
    eps      = 1e-10
    mean_val = float(np.mean(x))
    std_val  = float(np.std(x))
    rms_val  = float(np.sqrt(np.mean(x ** 2)))
    peak_val = float(np.max(xabs))
    mean_abs  = float(np.mean(xabs))
    mean_sqrt = float(np.mean(np.sqrt(xabs))) ** 2
    crest_factor     = peak_val / (rms_val   + eps)
    impulse_factor   = peak_val / (mean_abs  + eps)
    shape_factor     = rms_val  / (mean_abs  + eps)
    clearance_factor = peak_val / (mean_sqrt + eps)
    if std_val > eps:
        z        = (x - mean_val) / std_val
        kurtosis = float(np.mean(z ** 4))
        skewness = float(np.mean(z ** 3))
    else:
        kurtosis = 0.0
        skewness = 0.0
    thd   = compute_thd(x)
    sinad = compute_sinad(x)
    return [
        mean_val, std_val, rms_val, peak_val,
        crest_factor, impulse_factor, shape_factor, clearance_factor,
        kurtosis, skewness, thd, sinad
    ]


def extract_cycle_features(cycle):
    features = []
    for phase_idx in range(N_PHASES):
        signal = cycle[phase_idx, :]
        coeffs = pywt.wavedec(signal, WAVELET, level=DWT_LEVEL)
        for band_coeffs in coeffs:
            features.extend(extract_band_features(band_coeffs))
    return features


def extract_features_from_cycles(cycles, set_name):
    n        = len(cycles)
    features = np.zeros((n, N_FEATURES), dtype=np.float32)
    every    = max(1, n // 10)
    print('  Extracting from ' + set_name + ' (' + str(n) + ' cycles)...')
    for i in range(n):
        features[i, :] = extract_cycle_features(cycles[i])
        if (i + 1) % every == 0 or (i + 1) == n:
            print('    ' + str(i + 1) + '/' + str(n) +
                  '  (' + str(round(100 * (i + 1) / n, 1)) + '%)')
    print('  Done -> shape: ' + str(features.shape))
    return features


# ================================================================
#  STEP 1 - DOWNSAMPLE CLASS 0 IN TRAINING CYCLES ONLY
# ================================================================
print('=' * 65)
print('PHASE C - DOWNSAMPLING + DWT FEATURE EXTRACTION + SCALING')
print('=' * 65)
print()
print('Step 1: Downsampling class 0 in training cycles...')
print()

cls0_idx = np.where(y_train == 0)[0]
cls1_idx = np.where(y_train == 1)[0]
cls2_idx = np.where(y_train == 2)[0]

n_cls0 = len(cls0_idx)
n_cls1 = len(cls1_idx)
n_cls2 = len(cls2_idx)
target = n_cls1

print('  Before downsampling:')
print('    Class 0 (Non-islanding) : ' + str(n_cls0) + ' cycles')
print('    Class 1 (Islanding)     : ' + str(n_cls1) + ' cycles  <- reference')
print('    Class 2 (Line Fault)    : ' + str(n_cls2) + ' cycles')
print('    Total                   : ' + str(len(y_train)) + ' cycles')
print()

rng          = np.random.default_rng(42)
cls0_sampled = rng.choice(cls0_idx, size=target, replace=False)
bal_idx      = np.sort(np.concatenate([cls0_sampled, cls1_idx, cls2_idx]))
X_train_bal  = X_train_cycles[bal_idx]
y_train_bal  = y_train[bal_idx]

print('  After downsampling (training only):')
for cls in range(3):
    count = int(np.sum(y_train_bal == cls))
    print('    Class ' + str(cls) + ' (' + CLASS_NAMES[cls] + '): ' + str(count) + ' cycles')
print('    Total : ' + str(len(y_train_bal)) + ' cycles')
print()
print('  Validation and test sets kept at full size (no downsampling).')
print()

print("X_train_bal:", X_train_bal.shape)
print("y_train_bal:", y_train_bal.shape)
print("X_val_cycles:", X_val_cycles.shape)
print("y_val:", y_val.shape)

# ================================================================
#  STEP 2 - DWT FEATURE EXTRACTION
# ================================================================
print('Step 2: DWT Feature Extraction')
print('  Wavelet  : ' + WAVELET)
print('  Level    : ' + str(DWT_LEVEL))
print('  Bands    : cA2 (0-480Hz,    16 coeff)')
print('             cD2 (480-960Hz,  16 coeff)')
print('             cD1 (960-1920Hz, 32 coeff)')
print('  Features : 3 phases x 3 bands x 12 stats = ' + str(N_FEATURES))
print('  Spearman : SKIPPED - all 108 features passed to MLP')
print()

X_train_features = extract_features_from_cycles(X_train_bal,   'Training (balanced)')
print()
X_val_features   = extract_features_from_cycles(X_val_cycles,  'Validation')
print()
X_test_features  = extract_features_from_cycles(X_test_cycles, 'Test')
print()

# Sanity check
print('  Sanity check:')
all_ok = True
for sname, feats in [
    ('Training',   X_train_features),
    ('Validation', X_val_features),
    ('Test',       X_test_features)
]:
    n_nan  = int(np.sum(np.isnan(feats)))
    n_inf  = int(np.sum(np.isinf(feats)))
    status = 'OK' if n_nan == 0 and n_inf == 0 else 'WARNING'
    if status == 'WARNING':
        all_ok = False
    print('    ' + sname + ' -> NaN: ' + str(n_nan) +
          '  Inf: ' + str(n_inf) + '  ' + status)
if all_ok:
    print('  All feature arrays clean - no NaN or Inf values.')
print()


# Feature names
FEATURE_NAMES = []
for phase in ['Va', 'Vb', 'Vc']:
    for band in BAND_NAMES:
        for stat in STAT_NAMES:
            FEATURE_NAMES.append(phase + '_' + band + '_' + stat)

assert len(FEATURE_NAMES) == len(set(FEATURE_NAMES)), 'Duplicate feature names!'
print('  Feature names: ' + str(len(FEATURE_NAMES)) + ' (all unique)')
print()


# ================================================================
#  STEP 3 - STANDARDSCALER
#  Fit on balanced training set only
#  Transform all three sets
# ================================================================
print('Step 3: Applying StandardScaler...')
print('  Fit on balanced training set only.')
print('  Transform applied to training, validation and test.')
print()

scaler         = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_features)
X_val_scaled   = scaler.transform(X_val_features)
X_test_scaled  = scaler.transform(X_test_features)

print('  Post-scaling verification (should be ~0 mean, ~1 std):')
print('    Training mean (first 5): ' +
      str([round(float(v), 4) for v in X_train_scaled[:, :5].mean(axis=0)]))
print('    Training std  (first 5): ' +
      str([round(float(v), 4) for v in X_train_scaled[:, :5].std(axis=0)]))
print()


# ================================================================
#  FINAL SUMMARY
# ================================================================
print('=' * 65)
print('PHASE C COMPLETE - FINAL ARRAY SHAPES')
print('=' * 65)
print()
print('  X_train_scaled : ' + str(X_train_scaled.shape) +
      '  y_train_bal : ' + str(y_train_bal.shape))
print('  X_val_scaled   : ' + str(X_val_scaled.shape) +
      '  y_val       : ' + str(y_val.shape))
print('  X_test_scaled  : ' + str(X_test_scaled.shape) +
      '  y_test      : ' + str(y_test.shape))
print()
print('  Total features : ' + str(N_FEATURES) + ' (all kept, no Spearman filtering)')
print()

print('  Class distribution:')
for set_name, labels in [
    ('Training (balanced)', y_train_bal),
    ('Validation (original)', y_val),
    ('Test (original)', y_test),
]:
    total = len(labels)
    print('  ' + set_name + ' (' + str(total) + ' cycles):')
    for cls in range(3):
        count = int(np.sum(labels == cls))
        pct   = round(100 * count / total, 1)
        print('    Class ' + str(cls) + ' (' + CLASS_NAMES[cls] + '): '
              + str(count) + ' (' + str(pct) + '%)')
    print()

print('  Ready for Phase D (MLP classifier training)')

print("X_train_bal:", X_train_bal.shape)
print("y_train_bal:", y_train_bal.shape)
print("X_val_cycles:", X_val_cycles.shape)
print("y_val:", y_val.shape)
print("X_test_cycles:", X_test_cycles.shape)
print("y_test:", y_test.shape)

tf.config.optimizer.set_jit(False)

# ================================================================
#  BLOCK 1 — TRAIN CNN + EVALUATE ON TRAINING & VALIDATION
# ================================================================
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import itertools

# --- Reproducibility ---
np.random.seed(42)
tf.random.set_seed(42)

CLASS_NAMES = ["Non-islanding", "Islanding", "Line Fault"]

# ================================================================
#  Inspect existing arrays and reshape if needed
# ================================================================
print("Existing data shapes:")
print(f"  X_train_bal: {X_train_bal.shape}")
print(f"  X_val_bal:   {X_val_cycles.shape}")
print(f"  y_train:     {y_train_bal.shape}, classes: {np.unique(y_train)}")

if X_train_bal.shape[1] == 3 and X_train_bal.shape[2] == 64:
    print("\nTransposing from (N, 3, 64) to (N, 64, 3)...")
    X_train_cnn = np.transpose(X_train_bal, (0, 2, 1)).astype(np.float32)
    X_val_cnn   = np.transpose(X_val_cycles,   (0, 2, 1)).astype(np.float32)
elif X_train_bal.shape[1] == 64 and X_train_bal.shape[2] == 3:
    print("\nAlready in (N, 64, 3) format.")
    X_train_cnn = X_train_bal.astype(np.float32)
    X_val_cnn   = X_val_cycles.astype(np.float32)
else:
    raise ValueError(f"Unexpected shape {X_train_bal.shape}")

print(f"  X_train_cnn shape: {X_train_cnn.shape}")
print(f"  X_val_cnn shape:   {X_val_cnn.shape}")

# ================================================================
#  Build CNN
# ================================================================
def build_cnn(input_shape=(64, 3), n_classes=3):
    model = models.Sequential([
        layers.Input(shape=input_shape),

        layers.Conv1D(32, kernel_size=5, padding='same', activation='relu'),
        layers.Conv1D(32, kernel_size=5, padding='same', activation='relu'),
        layers.MaxPooling1D(pool_size=2),

        layers.Conv1D(64, kernel_size=5, padding='same', activation='relu'),
        layers.Conv1D(64, kernel_size=5, padding='same', activation='relu'),
        layers.MaxPooling1D(pool_size=2),

        layers.Conv1D(128, kernel_size=3, padding='same', activation='relu'),
        layers.GlobalAveragePooling1D(),
        layers.Dropout(0.4),

        layers.Dense(64, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(n_classes, activation='softmax')
    ])
    return model

cnn_model = build_cnn()
cnn_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
cnn_model.summary()

# ================================================================
#  Train
# ================================================================
early_stop = callbacks.EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True, verbose=1
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor='val_loss', factor=0.5, patience=5, min_lr=1e-6, verbose=1
)

history = cnn_model.fit(
    X_train_cnn, y_train_bal,
    validation_data=(X_val_cnn, y_val),
    epochs=250,
    batch_size=128,
    callbacks=[early_stop, reduce_lr],
    verbose=2
)

# ================================================================
#  Evaluate on training and validation sets
# ================================================================
print("\n" + "=" * 60)
print("CNN — TRAINING & VALIDATION RESULTS")
print("=" * 60)

y_train_pred_cnn = cnn_model.predict(X_train_cnn, verbose=0).argmax(axis=1)
y_val_pred_cnn   = cnn_model.predict(X_val_cnn,   verbose=0).argmax(axis=1)

for name, y_true, y_pred in [
    ("Training",   y_train_bal, y_train_pred_cnn),
    ("Validation", y_val,   y_val_pred_cnn),
]:
    acc = accuracy_score(y_true, y_pred) * 100
    print(f"\n--- {name} | Accuracy: {acc:.2f}% ---")
    print(classification_report(y_true, y_pred,
                                target_names=CLASS_NAMES, digits=4))

# ================================================================
#  Plot training history
# ================================================================
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].plot(history.history['loss'], label='train')
axes[0].plot(history.history['val_loss'], label='val')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss')
axes[0].set_title('CNN Training Loss'); axes[0].legend(); axes[0].grid(alpha=0.3)

axes[1].plot(history.history['accuracy'], label='train')
axes[1].plot(history.history['val_accuracy'], label='val')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Accuracy')
axes[1].set_title('CNN Training Accuracy'); axes[1].legend(); axes[1].grid(alpha=0.3)
plt.tight_layout()
plt.savefig(FIGURES_PATH + 'cnn_training_history.png', dpi=150, bbox_inches='tight')
plt.show()

# ================================================================
#  Save model for use in Block 2
# ================================================================
cnn_model.save('/content/drive/MyDrive/Final Year Project/Islanding_project/'
               'Dataset/Islanding-Detection-in-Colab/Outputs/models/cnn_islanding.keras')
print("\nCNN model saved to Drive — ready for test evaluation in Block 2")

print(f"X_train_bal shape: {X_train_bal.shape}")
print(f"Min/Max values: [{X_train_bal.min():.3f}, {X_train_bal.max():.3f}]")
print(f"First 5 values from sample 0, phase 0:")
print(X_train_bal[0, 0, :5] if X_train_bal.shape[1] == 3 else X_train_bal[0, :5, 0])

# Check actual peak distribution across all training cycles
peak_per_cycle = np.max(np.abs(X_train_bal), axis=(1, 2))
print(f"Peak voltage per cycle:")
print(f"  Min:    {peak_per_cycle.min():.3f}")
print(f"  Max:    {peak_per_cycle.max():.3f}")
print(f"  Mean:   {peak_per_cycle.mean():.3f}")
print(f"  Median: {np.median(peak_per_cycle):.3f}")

DATA_PATH   = '/content/drive/MyDrive/Final Year Project/Islanding_project/Dataset/Islanding-Detection-in-Colab/Dataset/scaled_dataset/'
FIG_PATH    = '/content/drive/MyDrive/Final Year Project/Islanding_project/Dataset/Islanding-Detection-in-Colab/Outputs/Figures/'
# --- Cell 2: Load arrays ---
X_train = np.load(DATA_PATH + 'X_train_scaled.npy')
X_val   = np.load(DATA_PATH + 'X_val_scaled.npy')
X_test  = np.load(DATA_PATH + 'X_test_scaled.npy')
y_train = np.load(DATA_PATH + 'y_train_bal.npy')
y_val   = np.load(DATA_PATH + 'y_val.npy')
y_test  = np.load(DATA_PATH + 'y_test.npy')

import joblib
!pip install xgboost
save_path   = '/content/drive/MyDrive/Final Year Project/Islanding_project/Dataset/Islanding-Detection-in-Colab/Outputs/models/'

xgb_model = joblib.load(save_path + 'xgb_model.pkl')
#print("XGBoost model loaded from Drive.")

# ================================================================
#  BLOCK 2 — TEST SET EVALUATION + CNN vs XGBoost COMPARISON
# ================================================================
import numpy as np
import matplotlib.pyplot as plt
import itertools
from sklearn.metrics import (classification_report, confusion_matrix,
                              accuracy_score, precision_recall_fscore_support)

CLASS_NAMES = ["Non-islanding", "Islanding", "Line Fault"]

# ================================================================
#  Reshape test data the same way as Block 1
# ================================================================
print(f"X_test_bal shape: {X_test_cycles.shape}")

if X_test_cycles.shape[1] == 3 and X_test_cycles.shape[2] == 64:
    X_test_cnn = np.transpose(X_test_cycles, (0, 2, 1)).astype(np.float32)
    print(f"Transposed to: {X_test_cnn.shape}")
elif X_test_cycles.shape[1] == 64 and X_test_cycles.shape[2] == 3:
    X_test_cnn = X_test_cycles.astype(np.float32)

# ================================================================
#  CNN test set predictions
# ================================================================
y_test_pred_cnn = cnn_model.predict(X_test_cnn, verbose=0).argmax(axis=1)
acc_cnn = accuracy_score(y_test, y_test_pred_cnn) * 100

print("\n" + "=" * 60)
print(f"CNN — TEST SET | Accuracy: {acc_cnn:.2f}%")
print("=" * 60)
print(classification_report(y_test, y_test_pred_cnn,
                            target_names=CLASS_NAMES, digits=4))

# ================================================================
#  XGBoost test set predictions (assumes xgb_model is in memory)
# ================================================================
# y_test_pred should already exist from your XGBoost notebook
# If not, regenerate it:
y_test_pred_xgb = xgb_model.predict(X_test)
acc_xgb = accuracy_score(y_test, y_test_pred_xgb) * 100

print("\n" + "=" * 60)
print(f"XGBoost — TEST SET | Accuracy: {acc_xgb:.2f}%")
print("=" * 60)
print(classification_report(y_test, y_test_pred_xgb,
                            target_names=CLASS_NAMES, digits=4))

# ================================================================
#  Side-by-side confusion matrices
# ================================================================
def plot_cm(ax, cm, title, class_names):
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
    ax.imshow(cm_norm, cmap=plt.cm.Blues, vmin=0, vmax=1)
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xticks(np.arange(len(class_names)))
    ax.set_xticklabels(class_names, rotation=30, ha='right', fontsize=9)
    ax.set_yticks(np.arange(len(class_names)))
    ax.set_yticklabels(class_names, fontsize=9)
    ax.set_ylabel('True'); ax.set_xlabel('Predicted')
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        color = "white" if cm_norm[i, j] > 0.5 else "black"
        ax.text(j, i, f"{cm[i,j]:,}\n({cm_norm[i,j]*100:.1f}%)",
                ha="center", va="center", fontsize=8, color=color)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
plot_cm(axes[0], confusion_matrix(y_test, y_test_pred_cnn),
        f"CNN — Test\n(Acc: {acc_cnn:.2f}%)", CLASS_NAMES)
plot_cm(axes[1], confusion_matrix(y_test, y_test_pred_xgb),
        f"XGBoost — Test\n(Acc: {acc_xgb:.2f}%)", CLASS_NAMES)
fig.suptitle("Test Set Confusion Matrices — CNN vs XGBoost",
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(FIG_PATH + 'cnn_vs_xgb_confusion.png', dpi=150, bbox_inches='tight')
plt.show()

# ================================================================
#  Per-class metrics comparison (bar chart)
# ================================================================
metrics_cnn = precision_recall_fscore_support(y_test, y_test_pred_cnn, labels=[0,1,2])
metrics_xgb = precision_recall_fscore_support(y_test, y_test_pred_xgb, labels=[0,1,2])

# Unpack
prec_cnn, rec_cnn, f1_cnn = metrics_cnn[0], metrics_cnn[1], metrics_cnn[2]
prec_xgb, rec_xgb, f1_xgb = metrics_xgb[0], metrics_xgb[1], metrics_xgb[2]

x = np.arange(len(CLASS_NAMES))
width = 0.35

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
for ax, (m_name, cnn_vals, xgb_vals) in zip(axes, [
    ("Precision", prec_cnn, prec_xgb),
    ("Recall",    rec_cnn,  rec_xgb),
    ("F1-Score",  f1_cnn,   f1_xgb)
]):
    bars1 = ax.bar(x - width/2, cnn_vals, width, label='CNN', color='#FF5722')
    bars2 = ax.bar(x + width/2, xgb_vals, width, label='XGBoost', color='#2196F3')
    ax.set_ylabel(m_name); ax.set_title(f'Test Set — {m_name}')
    ax.set_xticks(x); ax.set_xticklabels(CLASS_NAMES, rotation=20, ha='right')
    ax.set_ylim([0, 1.05]); ax.legend(); ax.grid(axis='y', alpha=0.3)
    for bars in [bars1, bars2]:
        for bar in bars:
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                    f'{bar.get_height():.3f}', ha='center', fontsize=8)

fig.suptitle("CNN vs XGBoost — Test Set Per-Class Metrics",
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(FIG_PATH + 'cnn_vs_xgb_metrics.png', dpi=150, bbox_inches='tight')
plt.show()

# ================================================================
#  Summary table
# ================================================================
print("\n" + "=" * 80)
print("  TEST SET COMPARISON — CNN vs XGBoost")
print("=" * 80)
print(f"\n  {'Metric':<35} {'CNN':>10} {'XGBoost':>10} {'Δ':>10}")
print("  " + "-" * 70)

# Overall accuracy
delta = acc_cnn - acc_xgb
arrow = "▲" if delta > 0 else ("▼" if delta < 0 else "—")
print(f"  {'Overall Accuracy (%)':<35} {acc_cnn:>10.2f} {acc_xgb:>10.2f} "
      f"{arrow}{abs(delta):>+8.2f}")

# Per class
for i, name in enumerate(CLASS_NAMES):
    print(f"\n  {name:<35}")
    for m_name, cnn_v, xgb_v in [
        ("  Precision", prec_cnn[i], prec_xgb[i]),
        ("  Recall",    rec_cnn[i],  rec_xgb[i]),
        ("  F1-Score",  f1_cnn[i],   f1_xgb[i])
    ]:
        d = cnn_v - xgb_v
        a = "▲" if d > 0 else ("▼" if d < 0 else "—")
        print(f"  {m_name:<33} {cnn_v:>10.4f} {xgb_v:>10.4f} {a}{abs(d):>+8.4f}")

print("\n" + "=" * 80)

import joblib

# Save the scaler
joblib.dump(scaler, '/content/drive/MyDrive/Final Year Project/Islanding_project/Dataset/Islanding-Detection-in-Colab/Outputs/scaler.pkl')
print("Scaler saved.")

from sklearn.decomposition import PCA

# ================================================================
#  PCA VISUALISATION - X_train_scaled and X_val_scaled
#
#  Projects 108-dimensional feature space down to 2 principal
#  components and plots class separation.
#
#  Figure 1: Training set PCA scatter
#  Figure 2: Validation set PCA scatter
#  Figure 3: Training + Validation overlaid
#  Figure 4: Explained variance plot
# ================================================================

CLASS_NAMES  = {0: 'Non-islanding', 1: 'Islanding', 2: 'Line Fault'}
CLASS_COLORS = {0: '#2196F3', 1: '#F44336', 2: '#FF9800'}
ALPHA        = 0.3
SIZE         = 8


# ================================================================
#  FIT PCA ON TRAINING SET ONLY
#  Transform both training and validation using same PCA
# ================================================================
print('Fitting PCA on training set...')

pca          = PCA(n_components=10, random_state=42)
pca.fit(X_train_scaled)

train_pca    = pca.transform(X_train_scaled)   # (N_train, 10)
val_pca      = pca.transform(X_val_scaled)     # (N_val, 10)

var_ratio    = pca.explained_variance_ratio_
var_pc1      = round(float(var_ratio[0]) * 100, 2)
var_pc2      = round(float(var_ratio[1]) * 100, 2)
var_total_2  = round(float(np.sum(var_ratio[:2])) * 100, 2)
var_total_10 = round(float(np.sum(var_ratio)) * 100, 2)

print('  PC1 variance explained : ' + str(var_pc1) + '%')
print('  PC2 variance explained : ' + str(var_pc2) + '%')
print('  PC1+PC2 combined       : ' + str(var_total_2) + '%')
print('  Top 10 PCs combined    : ' + str(var_total_10) + '%')
print()


# ================================================================
#  FIGURE 1 - TRAINING SET PCA SCATTER
# ================================================================
fig1, ax1 = plt.subplots(1, 1, figsize=(10, 7))
fig1.suptitle(
    'PCA Scatter - Training Set (balanced)\n'
    'PC1 (' + str(var_pc1) + '%) vs PC2 (' + str(var_pc2) + '%)'
    '  |  Combined variance: ' + str(var_total_2) + '%',
    fontsize=12, fontweight='bold')

for cls in range(3):
    mask = y_train_bal == cls
    ax1.scatter(
        train_pca[mask, 0],
        train_pca[mask, 1],
        c=CLASS_COLORS[cls],
        label=CLASS_NAMES[cls] + ' (' + str(int(np.sum(mask))) + ')',
        alpha=ALPHA,
        s=SIZE,
        rasterized=True
    )

ax1.set_xlabel('PC1 (' + str(var_pc1) + '% variance)', fontsize=10)
ax1.set_ylabel('PC2 (' + str(var_pc2) + '% variance)', fontsize=10)
ax1.legend(fontsize=10, markerscale=3)
ax1.grid(alpha=0.3)
ax1.axhline(0, color='gray', linewidth=0.5, linestyle='--')
ax1.axvline(0, color='gray', linewidth=0.5, linestyle='--')

plt.tight_layout()
plt.savefig(FIGURES_PATH + 'pca_training.png', dpi=150, bbox_inches='tight')
plt.show()
print('Figure 1 saved: pca_training.png')


# ================================================================
#  FIGURE 2 - VALIDATION SET PCA SCATTER
# ================================================================
fig2, ax2 = plt.subplots(1, 1, figsize=(10, 7))
fig2.suptitle(
    'PCA Scatter - Validation Set (original distribution)\n'
    'PC1 (' + str(var_pc1) + '%) vs PC2 (' + str(var_pc2) + '%)'
    '  |  Same PCA fitted on training set',
    fontsize=12, fontweight='bold')

for cls in range(3):
    mask = y_val == cls
    ax2.scatter(
        val_pca[mask, 0],
        val_pca[mask, 1],
        c=CLASS_COLORS[cls],
        label=CLASS_NAMES[cls] + ' (' + str(int(np.sum(mask))) + ')',
        alpha=ALPHA,
        s=SIZE,
        rasterized=True
    )

ax2.set_xlabel('PC1 (' + str(var_pc1) + '% variance)', fontsize=10)
ax2.set_ylabel('PC2 (' + str(var_pc2) + '% variance)', fontsize=10)
ax2.legend(fontsize=10, markerscale=3)
ax2.grid(alpha=0.3)
ax2.axhline(0, color='gray', linewidth=0.5, linestyle='--')
ax2.axvline(0, color='gray', linewidth=0.5, linestyle='--')

plt.tight_layout()
plt.savefig(FIGURES_PATH + 'pca_validation.png', dpi=150, bbox_inches='tight')
plt.show()
print('Figure 2 saved: pca_validation.png')


# ================================================================
#  FIGURE 3 - TRAINING + VALIDATION OVERLAID
#  Training = filled circles, Validation = triangles
#  Shows if val distribution matches training distribution
# ================================================================
fig3, ax3 = plt.subplots(1, 1, figsize=(10, 7))
fig3.suptitle(
    'PCA Scatter - Training vs Validation Overlay\n'
    'Circles = Training  |  Triangles = Validation',
    fontsize=12, fontweight='bold')

for cls in range(3):
    tr_mask  = y_train_bal == cls
    val_mask = y_val == cls
    # Training: filled circles
    ax3.scatter(
        train_pca[tr_mask, 0], train_pca[tr_mask, 1],
        c=CLASS_COLORS[cls], marker='o',
        label=CLASS_NAMES[cls] + ' train',
        alpha=0.2, s=SIZE, rasterized=True
    )
    # Validation: triangles
    ax3.scatter(
        val_pca[val_mask, 0], val_pca[val_mask, 1],
        c=CLASS_COLORS[cls], marker='^',
        label=CLASS_NAMES[cls] + ' val',
        alpha=0.4, s=SIZE + 4, rasterized=True
    )

ax3.set_xlabel('PC1 (' + str(var_pc1) + '% variance)', fontsize=10)
ax3.set_ylabel('PC2 (' + str(var_pc2) + '% variance)', fontsize=10)
ax3.legend(fontsize=8, markerscale=3, ncol=2)
ax3.grid(alpha=0.3)
ax3.axhline(0, color='gray', linewidth=0.5, linestyle='--')
ax3.axvline(0, color='gray', linewidth=0.5, linestyle='--')

plt.tight_layout()
plt.savefig(FIGURES_PATH + 'pca_train_val_overlay.png', dpi=150, bbox_inches='tight')
plt.show()
print('Figure 3 saved: pca_train_val_overlay.png')


# ================================================================
#  FIGURE 4 - EXPLAINED VARIANCE PLOT
#  Shows how many PCs are needed to capture the variance
# ================================================================
fig4, axes4 = plt.subplots(1, 2, figsize=(12, 4))
fig4.suptitle('PCA Explained Variance - Top 10 Components',
              fontsize=12, fontweight='bold')

pcs = np.arange(1, 11)

# Individual variance per component
axes4[0].bar(pcs, var_ratio * 100, color='steelblue', alpha=0.8)
axes4[0].set_xlabel('Principal Component', fontsize=10)
axes4[0].set_ylabel('Variance Explained (%)', fontsize=10)
axes4[0].set_title('Individual Variance per PC', fontsize=10)
axes4[0].set_xticks(pcs)
axes4[0].grid(alpha=0.3, axis='y')
for i, v in enumerate(var_ratio * 100):
    axes4[0].text(pcs[i], v + 0.3, str(round(float(v), 1)) + '%',
                 ha='center', fontsize=7)

# Cumulative variance
cumvar = np.cumsum(var_ratio) * 100
axes4[1].plot(pcs, cumvar, 'o-', color='darkorange', linewidth=2)
axes4[1].axhline(90, color='red', linestyle='--', linewidth=1, label='90% threshold')
axes4[1].axhline(95, color='green', linestyle='--', linewidth=1, label='95% threshold')
axes4[1].set_xlabel('Number of Principal Components', fontsize=10)
axes4[1].set_ylabel('Cumulative Variance Explained (%)', fontsize=10)
axes4[1].set_title('Cumulative Variance', fontsize=10)
axes4[1].set_xticks(pcs)
axes4[1].legend(fontsize=8)
axes4[1].grid(alpha=0.3)
for i, v in enumerate(cumvar):
    axes4[1].text(pcs[i], v + 0.5, str(round(float(v), 1)) + '%',
                 ha='center', fontsize=7)

plt.tight_layout()
plt.savefig(FIGURES_PATH + 'pca_variance.png', dpi=150, bbox_inches='tight')
plt.show()
print('Figure 4 saved: pca_variance.png')


# ================================================================
#  PRINT SUMMARY
# ================================================================
print()
print('=' * 55)
print('PCA SUMMARY')
print('=' * 55)
print('  Input dimensions : 108 features')
print('  PC1 variance     : ' + str(var_pc1) + '%')
print('  PC2 variance     : ' + str(var_pc2) + '%')
print('  PC1+PC2 combined : ' + str(var_total_2) + '%')
print('  Top 10 PCs       : ' + str(var_total_10) + '%')
print()
print('  Interpretation:')
print('    Well separated clusters -> MLP should perform well')
print('    Overlapping clusters    -> MLP may struggle but note')
print('    that PCA is linear and MLP uses non-linear boundaries')
print('    so overlap in 2D does not mean poor classification')

"""MLP Classifier"""

tf.random.set_seed(1234)
model = Sequential(

        [tf.keras.Input(shape=(108,)),
         tf.keras.layers.Dense(units=128, activation = "relu", kernel_regularizer=tf.keras.regularizers.l2(0.001)),
         tf.keras.layers.Dense(units=64, activation = "relu", kernel_regularizer=tf.keras.regularizers.l2(0.001)),
         tf.keras.layers.Dense(units=3, activation = "linear")

    ], name = "model"
)

model.summary()

[layer1, layer2, layer3] = model.layers

# Define callbacks first
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=10,
    min_delta=0.001,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=5,
    min_lr=1e-6,
    verbose=1
)

print('Callbacks defined.')

model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), metrics=["accuracy"]
)

print(model.metrics_names)

history = model.fit(
    X_train_scaled, y_train_bal,
    epochs=200,
    batch_size=256,
    validation_data=(X_val_scaled, y_val),
    callbacks=[early_stopping, reduce_lr],
    verbose=1
)

print(f"x-validation shape{X_val_scaled.shape}")
print(f"y-validation shape{y_val.shape}")

def eval_cat_err(y, yhat):
    """
    Calculate the categorization error
    Args:
      y    : (ndarray  Shape (m,) or (m,1))  target value of each example
      yhat : (ndarray  Shape (m,) or (m,1))  predicted value of each example
    Returns:|
      err: (scalar)
    """
    m = len(y)
    incorrect = 0
    for i in range(m):
        if yhat[i] != y[i]:
            incorrect += 1
    err = incorrect/m
    return(err)

model_predict = lambda Xl: np.argmax(tf.nn.softmax(model.predict(Xl)).numpy(),axis=1)
training_cerror = eval_cat_err(y_train_bal, model_predict(X_train_scaled))

cv_cerr_r = eval_cat_err(y_val, model_predict(X_val_scaled))
print(f"training error: {training_cerror:0.3f}" )
print(f"Validation error: {cv_cerr_r:0.3f}" )

print(model.metrics_names)

"""Evaluation of Model Accuracy on Training and Validation Dataset"""

# Training accuracy
train_loss, train_acc = model.evaluate(X_train_scaled, y_train_bal, verbose=0)
print('Training accuracy   : ' + str(round(train_acc * 100, 2)) + '%')
print('Training loss       : ' + str(round(train_loss, 4)))
print()

# Validation accuracy
val_loss, val_acc = model.evaluate(X_val_scaled, y_val, verbose=0)
print('Validation accuracy : ' + str(round(val_acc * 100, 2)) + '%')
print('Validation loss     : ' + str(round(val_loss, 4)))

import matplotlib.pyplot as plt

# ================================================================
#  TRAINING HISTORY - LOSS AND ACCURACY CURVES
# ================================================================

total_epochs = len(history.history['loss'])
epochs_range = range(1, total_epochs + 1)

best_epoch   = int(np.argmin(history.history['val_loss'])) + 1

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Training History - Islanding MLP', fontsize=13, fontweight='bold')

# ── Loss curve ────────────────────────────────────────────────
axes[0].plot(epochs_range, history.history['loss'],
             color='steelblue', linewidth=1.5, label='Training loss')
axes[0].plot(epochs_range, history.history['val_loss'],
             color='darkorange', linewidth=1.5, label='Validation loss')
axes[0].axvline(best_epoch, color='red', linestyle='--',
                linewidth=1.0, label='Best epoch (' + str(best_epoch) + ')')
axes[0].set_title('Loss', fontsize=11)
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].legend(fontsize=9)
axes[0].grid(alpha=0.3)

# ── Accuracy curve ────────────────────────────────────────────
axes[1].plot(epochs_range, [v * 100 for v in history.history['accuracy']],
             color='steelblue', linewidth=1.5, label='Training accuracy')
axes[1].plot(epochs_range, [v * 100 for v in history.history['val_accuracy']],
             color='darkorange', linewidth=1.5, label='Validation accuracy')
axes[1].axvline(best_epoch, color='red', linestyle='--',
                linewidth=1.0, label='Best epoch (' + str(best_epoch) + ')')
axes[1].set_title('Accuracy', fontsize=11)
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Accuracy (%)')
axes[1].legend(fontsize=9)
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig(FIGURES_PATH + 'training_history.png', dpi=150, bbox_inches='tight')
plt.show()

print('Best epoch       : ' + str(best_epoch))
print('Best val loss    : ' + str(round(float(np.min(history.history['val_loss'])), 4)))
print('Best val accuracy: ' + str(round(float(history.history['val_accuracy'][best_epoch-1]) * 100, 2)) + '%')

tf.random.set_seed(1234)
lambdas = [0.0, 0.001, 0.01, 0.05, 0.1, 0.2, 0.3]
models=[None] * len(lambdas)

for i in range(len(lambdas)):
    lambda_ = lambdas[i]
    models[i] =  Sequential(
        [
            Dense(128, activation = 'relu', kernel_regularizer=tf.keras.regularizers.l2(lambda_)),
            Dense(64, activation = 'relu', kernel_regularizer=tf.keras.regularizers.l2(lambda_)),
            Dense(3, activation = 'linear')
        ]
    )
    models[i].compile(
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        optimizer=tf.keras.optimizers.Adam(0.01), metrics=["accuracy"]

    )

    models[i].fit(
    X_train_scaled, y_train_bal,
    epochs=200,
    batch_size=256,
    validation_data=(X_val_scaled, y_val),
    callbacks=[early_stopping, reduce_lr],
    verbose=1
    )
    print(f"Finished lambda = {lambda_}")

dlc = {
    "dlblue": "#0097e6",
    "dlorange": "#ff7f00",
    "dlgreen": "#00b894",
    "dlred": "#d63031",
    "dlyellow": "#fdcb6e",
    "dlpurple": "#a29bfe"
}

def plot_iterate(lambdas, models, X_train, y_train, X_cv, y_cv):
    err_train = np.zeros(len(lambdas))
    err_cv = np.zeros(len(lambdas))
    for i in range(len(models)):
        err_train[i] = eval_cat_err(y_train,np.argmax( models[i](X_train), axis=1))
        err_cv[i] = eval_cat_err(y_cv, np.argmax( models[i](X_cv), axis=1))

    fig, ax = plt.subplots(1,1,figsize=(6,4))
    fig.canvas.toolbar_visible = False
    fig.canvas.header_visible = False
    fig.canvas.footer_visible = False
    ax.set_title("error vs regularization",fontsize = 12)
    ax.plot(lambdas, err_train, marker='o', label="train error", color = dlc["dlblue"])
    ax.plot(lambdas, err_cv,    marker='o', label="cv error",    color = dlc["dlorange"])
    ax.set_xscale('log')
    ax.set_ylim(*ax.get_ylim())
    ax.set_xlabel("Regularization (lambda)",fontsize = 14)
    ax.set_ylabel("Error",fontsize = 14)
    ax.legend()
    fig.suptitle("Tuning Regularization",fontsize = 14)
    ax.text(0.05,0.14,"Training Error\nlower than CV",fontsize=12, ha='left',transform=ax.transAxes,color = dlc["dlblue"])
    ax.text(0.95,0.14,"Similar\nTraining, CV",    fontsize=12, ha='right',transform=ax.transAxes,color = dlc["dlblue"])
    plt.show()

from matplotlib.colors import ListedColormap, LinearSegmentedColormap
plot_iterate(lambdas, models, X_train_scaled, y_train_bal, X_val_scaled, y_val)

"""Final Evaluation on The Test Dataset"""

from sklearn.metrics import classification_report

# Test evaluation
test_loss, test_acc = model.evaluate(X_test_scaled, y_test, verbose=0)
print('=' * 50)
print('TEST SET RESULTS')
print('=' * 50)
print('Test accuracy : ' + str(round(test_acc * 100, 2)) + '%')
print('Test loss     : ' + str(round(test_loss, 4)))
print()

# Per class metrics
test_preds  = np.argmax(tf.nn.softmax(model.predict(X_test_scaled)), axis=1)
CLASS_NAMES = ['Non-islanding', 'Islanding', 'Line Fault']

print(classification_report(y_test, test_preds,
                             target_names=CLASS_NAMES, digits=4))

from sklearn.metrics import classification_report

# Test evaluation
training_loss, training_acc = model.evaluate(X_train_scaled, y_train_bal, verbose=0)
print('=' * 50)
print('TRAINING SET RESULTS')
print('=' * 50)
print('Training accuracy : ' + str(round(training_acc * 100, 2)) + '%')
print('Training loss     : ' + str(round(training_loss, 4)))
print()

# Per class metrics
train_preds  = np.argmax(tf.nn.softmax(model.predict(X_train_scaled)), axis=1)
CLASS_NAMES = ['Non-islanding', 'Islanding', 'Line Fault']

print(classification_report(y_train_bal, train_preds,
                             target_names=CLASS_NAMES, digits=4))

val_loss, val_acc = model.evaluate(X_val_scaled, y_val, verbose=0)
print('=' * 50)
print('Validation SET RESULTS')
print('=' * 50)
print('Validation accuracy : ' + str(round(test_acc * 100, 2)) + '%')
print('Validation loss     : ' + str(round(test_loss, 4)))
print()

# Per class metrics
val_preds  = np.argmax(tf.nn.softmax(model.predict(X_val_scaled)), axis=1)
CLASS_NAMES = ['Non-islanding', 'Islanding', 'Line Fault']

print(classification_report(y_val, val_preds,
                             target_names=CLASS_NAMES, digits=4))

# Save model weights
import os
os.makedirs(MODELS_PATH, exist_ok=True)
model.save(MODELS_PATH + 'mlp_islanding.keras')
print('Model saved.')

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from sklearn.metrics import confusion_matrix
import itertools
import os

CLASS_NAMES = ["Non-islanding", "Islanding", "Line Fault"]

def plot_confusion_matrix(ax, cm, title, class_names):
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
    im = ax.imshow(cm_norm, interpolation='nearest', cmap=plt.cm.Blues, vmin=0, vmax=1)
    ax.set_title(title, fontsize=13, fontweight='bold', pad=10)
    tick_marks = np.arange(len(class_names))
    ax.set_xticks(tick_marks)
    ax.set_xticklabels(class_names, rotation=30, ha='right', fontsize=9)
    ax.set_yticks(tick_marks)
    ax.set_yticklabels(class_names, fontsize=9)
    ax.set_ylabel('True Label', fontsize=10)
    ax.set_xlabel('Predicted Label', fontsize=10)

    thresh = 0.5
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        count = cm[i, j]
        pct = cm_norm[i, j] * 100
        color = "white" if cm_norm[i, j] > thresh else "black"
        ax.text(j, i, f"{count:,}\n({pct:.1f}%)",
                ha="center", va="center", fontsize=8, color=color)
    return im

# --- Generate predictions ---
y_train_pred = np.argmax(model.predict(X_train_scaled, verbose=0), axis=1)
y_val_pred   = np.argmax(model.predict(X_val_scaled,   verbose=0), axis=1)
y_test_pred  = np.argmax(model.predict(X_test_scaled,  verbose=0), axis=1)

# --- Compute confusion matrices ---
cm_train = confusion_matrix(y_train_bal, y_train_pred)
cm_val   = confusion_matrix(y_val,       y_val_pred)
cm_test  = confusion_matrix(y_test,      y_test_pred)

# --- Plot ---
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

titles = [
    f"Training Set\n(Acc: 96.74%)",
    f"Validation Set — Original\n(Acc: 97.25%)",
    f"Test Set — Original (PRIMARY)\n(Acc: 97.61%)"
]
cms = [cm_train, cm_val, cm_test]

ims = []
for ax, cm, title in zip(axes, cms, titles):
    im = plot_confusion_matrix(ax, cm, title, CLASS_NAMES)
    ims.append(im)

# Shared colourbar
fig.subplots_adjust(right=0.88, wspace=0.35)
cbar_ax = fig.add_axes([0.91, 0.15, 0.015, 0.7])
fig.colorbar(ims[-1], cax=cbar_ax).set_label('Normalised Rate', fontsize=10)

fig.suptitle("Islanding Detection — Confusion Matrices", fontsize=15, fontweight='bold', y=1.02)

# Ensure the directory exists before saving
os.makedirs(FIGURES_PATH, exist_ok=True)
plt.savefig(FIGURES_PATH + 'phase_E_confusion_matrices.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("Saved to " + FIGURES_PATH + "phase_E_confusion_matrices.png")

"""# ================================================================
#  SAVE SCALED ARRAYS TO DRIVE
#  Run this once in your existing MLP notebook
# ================================================================

"""

import os

save_path = '/content/drive/MyDrive/Islanding_Project/outputs/'
os.makedirs(save_path, exist_ok=True)

np.save(save_path + 'X_train_scaled.npy', X_train_scaled);
np.save(save_path + 'X_val_scaled.npy',   X_val_scaled);
np.save(save_path + 'X_test_scaled.npy',  X_test_scaled);
np.save(save_path + 'y_train_bal.npy',    y_train_bal);
np.save(save_path + 'y_val.npy',          y_val);
np.save(save_path + 'y_test.npy',         y_test);

print("All arrays saved successfully.")

"""::"""